theme: minima
title: Campanile
future: true
paginate: 12

title: Campanile
author:
  name: 
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  Site for posts about my interests: the biotech industry, medicine, molecular biology, neuroscience, biorisk, science, consciousness, AI, innovation, decision making, philosophy, games, sci-fi, probability, and forecasting (among other things). I write to learn, mostly about biotech.
business_description: >
    For business enquiries: Please contact me by email <a class="u-email" href="mailto:">here</a> or on Twitter.

show_excerpts: false # set to true to show excerpts on the homepage


# Minima date format
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    - { platform: linkedin,       user_url: "" }
    - { platform: twitter,        user_url: "" }
    - { platform: rss,            user_url: "" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
  
plugins:
 - jekyll-seo-tag
 - jekyll-feed

feed:
 excerpt_only: true
